# Generated by Django 3.0.4 on 2020-04-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate_entry_app', '0002_auto_20200329_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancehistory',
            options={'verbose_name': 'Attendance history', 'verbose_name_plural': 'Attendance history'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.RenameField(
            model_name='attendancehistory',
            old_name='gate_id',
            new_name='gate',
        ),
        migrations.RenameField(
            model_name='attendancehistory',
            old_name='person_id',
            new_name='person',
        ),
    ]
