# Generated by Django 3.0.4 on 2020-05-09 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gate_entry_app', '0003_auto_20200401_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=30)),
                ('is_entry_device', models.BooleanField(default=True)),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gate_entry_app.Gate')),
            ],
        ),
    ]
